### PR TITLE
Adding a message board feature 

### PR DESCRIPTION
**Pull request by luke-hazelton**
very simple implementation

### CODE REVIEW

**Review by collinsjacob127 — DISMISSED** [review]
These seem fairly straightforward. The changes should be good as long as URLs are tested and work.

**Review by wwoah — DISMISSED** [review]
Nicely done

**Review by collinsjacob127 — APPROVED** [review]
Looks good after resolving conflicts.

**Review by Dcourt9712 — APPROVED** [review]
looks good

**Review by wwoah — APPROVED** [review]

**Pull request merged**
